services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - MODEL_PATH=/app/saved/model.keras
      - TOKENIZER_PATH=/app/saved/tokenizer.json
      - DATABASE_URL=sqlite:///phishguard.db
      - MAX_LEN=200
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      - VITE_API_URL=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
